name: advanced_course
packages:
  - features/**
  - Core/**


command:
  bootstrap:    
    environment:
      sdk: ^3.7.2
    dependencies:
      flutter:
        sdk: flutter
      dio: ^5.8.0+1
      get_it: ^8.0.3
      injectable: ^2.5.0
      json_annotation: ^4.9.0


      cupertino_icons: ^1.0.8
      melos: ^6.3.2

    dev_dependencies:
      flutter_test:
        sdk: flutter
      json_serializable: ^6.9.5
      flutter_lints: ^5.0.0
      build_runner: ^2.4.15
      injectable_generator: ^2.7.0


scripts:
  clean: melos clean
  cleanAndbootstrap : melos clean && melos bootstrap
  test: 
    run: melos exec flutter test
  update: flutter pub outdated
  upgrade: flutter pub upgrade --major-versions